version: "2"
services:
  namenode:
    image: jiahao0428/hadoop-spark-cluster
    hostname: namenode
    networks:
      - overlay
    depends_on:
      - mongodb
    extra_hosts:
      - "mongo:10.5.0.2"
      - "flume:10.5.0.4"
    command: "/etc/bootstrap.sh -d -namenode"
    dns: 8.8.8.8
    expose:
      - "22"
      - "8088"
      - "50090"
      - "19888"
      - "4040"
      - "8080"
      - "8001"
      - "4545"

  mongodb:
    image: mongo
    networks:
      - overlay
    hostname: mongo
  
  flume:
    image: jiahao0428/flume
    hostname: flume
    networks:
      - overlay
    depends_on:
      - namenode
    extra_hosts:
      - "namenode:10.5.0.3"
    environment:
      - FLUME_AGENT_NAME=a1
      - FLUME_CONF_FILE=/code/flume.conf
    expose:
      - "8001"
      - "4545"

networks:
  overlay:
    driver: overlay
    ipam:
      config:
        - subnet: 10.5.0.0/24
